name: Manual Deploy to Azure Web App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ''
          username: ${{ secrets.AZURE_WEBAPP_USERNAME }}
          password: ${{ secrets.AZURE_WEBAPP_PASSWORD }}
